# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import model_pb2 as model__pb2


class MoleculeTrainerStub(object):
    """Define the service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.optimize = channel.unary_unary(
                '/MoleculeTrainer/optimize',
                request_serializer=model__pb2.OptimizationConfig.SerializeToString,
                response_deserializer=model__pb2.OptimizationOutput.FromString,
                )
        self.train = channel.unary_unary(
                '/MoleculeTrainer/train',
                request_serializer=model__pb2.TrainingConfig.SerializeToString,
                response_deserializer=model__pb2.TrainingEnd.FromString,
                )


class MoleculeTrainerServicer(object):
    """Define the service
    """

    def optimize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def train(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MoleculeTrainerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'optimize': grpc.unary_unary_rpc_method_handler(
                    servicer.optimize,
                    request_deserializer=model__pb2.OptimizationConfig.FromString,
                    response_serializer=model__pb2.OptimizationOutput.SerializeToString,
            ),
            'train': grpc.unary_unary_rpc_method_handler(
                    servicer.train,
                    request_deserializer=model__pb2.TrainingConfig.FromString,
                    response_serializer=model__pb2.TrainingEnd.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MoleculeTrainer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MoleculeTrainer(object):
    """Define the service
    """

    @staticmethod
    def optimize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MoleculeTrainer/optimize',
            model__pb2.OptimizationConfig.SerializeToString,
            model__pb2.OptimizationOutput.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def train(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MoleculeTrainer/train',
            model__pb2.TrainingConfig.SerializeToString,
            model__pb2.TrainingEnd.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
